n1 = float(input("Numero 1: "))
n2 = float(input("Numero 2: "))
print("\n\n")
if n1 == n2: print("iguais")
elif n1 > n2: print(f"{n1} é maior  Numeros {n1} {n2}")
elif n2 > n1: print(f"{n2} é maior  Numeros {n2} {n1}")
else: print("erro")
